spring:
  profiles: default
  datasource:
    url: jdbc:mysql://localhost:3306/zm?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  http:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB
  application :
     name: "test"

server:
  address: "${HTTP_BIND_ADDRESS:0.0.0.0}"
  port: "${HTTP_BIND_PORT:18080}"

application:
  cors:
    allowed-origins: "*"
    allowed-methods: "GET, PUT, POST, DELETE, OPTIONS"
    allowed-headers: "*"
    exposed-headers: "X-Total-Count"
  async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 1000