spring:
  profiles: default
  data:
    mongodb:
      uri: mongodb://192.168.10.161:27017/test
  http:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB
  application :
     name: "sc"
server:
  address: "${HTTP_BIND_ADDRESS:0.0.0.0}"
  port: "${HTTP_BIND_PORT:18080}"